# Generated by Django 5.2.5 on 2025-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_barangay_is_default_city_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
